import * as Sentry from '@sentry/react-native';

export type MonitoringEventName =
  | 'auth_signin_success'
  | 'auth_signin_fail'
  | 'booking_create_success'
  | 'booking_create_fail'
  | 'message_send_success'
  | 'message_send_fail'
  | 'pro_purchase_started'
  | 'pro_purchase_succeeded'
  | 'pro_purchase_failed'
  | 'pro_restore_succeeded'
  | 'pro_restore_failed'
  | 'friends_match_entry_tapped'
  | 'friends_match_entry_failed'
  | 'metro_override_set'
  | 'metro_default_set'
  | 'metro_auto_mode_enabled'
  | 'metro_nearest_resolution_used'
  | 'friends_recommendations_v4_failed'
  | 'metro_resolve_success'
  | 'metro_resolve_failed'
  | 'location_data_blocked_read'
  | 'location_policy_denied'
  | 'meetup_proposal_sent'
  | 'meetup_proposal_accepted'
  | 'meetup_proposal_declined'
  | 'meetup_proposal_countered'
  | 'meetup_open_maps'
  | 'directions_request_success'
  | 'directions_request_fail'
  | 'directions_route_selected'
  | 'live_location_share_started'
  | 'live_location_share_stopped'
  | 'live_location_permission_denied'
  | 'live_location_cleanup_run'
  | 'google_maps_runtime_unavailable'
  | 'wingman_onboarding_step_viewed'
  | 'wingman_onboarding_step_completed'
  | 'wingman_onboarding_blocked'
  | 'wingman_agreement_accept_success'
  | 'wingman_agreement_accept_fail'
  | 'wingman_profile_setup_save_success'
  | 'wingman_profile_setup_save_fail'
  | 'id_verification_retry_started'
  | 'profile_photo_capture_started'
  | 'profile_photo_capture_failed_quality'
  | 'profile_photo_capture_failed_spoof_risk'
  | 'profile_photo_trust_promoted'
  | 'profile_photo_trust_revoked'
  | 'id_verification_start_blocked_identity_not_enabled'
  | 'safety_sos_triggered'
  | 'safety_sos_trigger_failed'
  | 'safety_checkin_safe_selected'
  | 'safety_checkin_unsafe_selected'
  | 'safety_audio_start'
  | 'safety_audio_start_attempt'
  | 'safety_audio_start_result'
  | 'safety_audio_state_changed'
  | 'safety_audio_interruption_handled'
  | 'safety_audio_recovery_restored'
  | 'safety_audio_stop'
  | 'safety_audio_autostart'
  | 'safety_audio_permission_denied'
  | 'safety_audio_storage_low_warning'
  | 'safety_audio_storage_critical_stop'
  | 'safety_audio_cleanup_run'
  | 'safety_audio_deleted'
  | 'safety_audio_cloud_upload_started'
  | 'safety_audio_cloud_upload_progress'
  | 'safety_audio_cloud_upload_succeeded'
  | 'safety_audio_cloud_upload_failed'
  | 'safety_audio_cloud_upload_retry_scheduled'
  | 'safety_audio_cloud_download_started'
  | 'safety_audio_cloud_download_succeeded'
  | 'safety_audio_cloud_download_failed'
  | 'safety_audio_cloud_deleted'
  | 'safety_audio_cloud_notice_shown'
  | 'safety_audio_cloud_grace_warning_shown'
  | 'emergency_contact_added'
  | 'emergency_contact_removed'
  | 'emergency_contact_verified'
  | 'emergency_live_location_started'
  | 'emergency_live_location_stopped'
  | 'safety_maintenance_run';

type EventPayload = Record<string, string | number | boolean | null | undefined>;

export function trackEvent(name: MonitoringEventName, payload: EventPayload = {}): void {
  Sentry.addBreadcrumb({
    category: 'product.event',
    level: 'info',
    message: name,
    data: payload,
  });
}
